### ISSUE TITLE
建议-作者可以去去SCP哈

### ISSUE THREAD

**Issue by fengmumu1** [deepspacecraft/impossible#1]
如题

**Comment by shuiRong** [comment]
[SCP基金会](http://scp-wiki-cn.wikidot.com/)欢迎作者投稿

**Comment by deepspacecraft** [comment]
The supernatural phenomenon should not exist in the real world.
So I closed this issue for the pseudo bug.

**Comment by madobet** [comment]
噗，我想了下也是 SCP 的感觉，不过更像科幻小说，话说你们这么冷嘲热讽的也不好让作者投稿了吧。作为 SCP 来说显得太零散了，不过总体还挺细致的，我感觉充实一下说不定还挺不错的。
